---
# apt
apt_packages:
  - apt-transport-https
  - bash-completion
  - iputils-ping
  - python3-pip
  - openssh-server
  - openssh-client
  - libkrb5-dev
  - krb5-user
  - gcc
  - sudo
  - nano
  - vim
  - git
  - curl
  - tmux
  - unzip
  - fzf

# brew
linuxbrew_install_tmp: /tmp/linuxbrew
linuxbrew_install_url: https://raw.githubusercontent.com/Homebrew/install/master/install.sh
brew_path: /home/linuxbrew/.linuxbrew/bin
brew_bin_path: "{{ brew_path }}/brew"
brew_packages:
  - bat
  - kubectl
  - helm
  - derailed/k9s/k9s
  - kubeseal
  - argocd
  - argocd-autopilot
  - krew
  - nvm

# krew
krew_bin_path: "{{ brew_path }}/kubectl-krew"
krew_version: latest
krew_user: "{{ linux_username }}"
krew_plugins:
  - "ingress-nginx"

# nvm
nvm_profile: "/home/{{ linux_username }}/.bashrc"
nodejs_version: '16'

# pip
pip_packages:
  - pykerberos==1.2.4

# resolv
resolv_nameserver_primary: '10.1.0.10'
resolv_nameserver_secondary: '173.16.48.4'
resolv_search: citrix-dch.local

# shell
bash_profile_scripts:
  - history.sh
  - brew.sh
  - krew.sh
  - kubectl-aliases.sh
  - kubectl-completion.sh

# workspace
workspace_dir: /home/{{ linux_username }}/source/repos
workspace_repos:
  - name: kubectl-aliases
    url: https://github.com/Davenport-Iowa/kubectl-aliases.git
