---
# apt
apt_packages:
  - apt-transport-https
  - bash-completion
  - iputils-ping
  - python3-pip
  - openssh-server
  - openssh-client
  - libkrb5-dev
  - krb5-user
  - gcc
  - sudo
  - nano
  - neovim
  - git
  - curl
  - tmux
  - unzip
  - fzf

# brew
linuxbrew_install_tmp: /tmp/linuxbrew
linuxbrew_install_url: https://raw.githubusercontent.com/Homebrew/install/master/install.sh
brew_path: /home/linuxbrew/.linuxbrew/bin
brew_bin_path: "{{ brew_path }}/brew"
brew_packages:
  - bat
  - kubectl
  - helm
  - derailed/k9s/k9s
  - kubeseal
  - argocd
  - argocd-autopilot
  - krew
  - nvm
  - gh
  - pnpm

# git
git_global_user_name: Jeremy Johnson
git_global_user_email: modernclassicgamer@gmail.com
git_global_credential_helper: store

# krew
krew_bin_path: "{{ brew_path }}/kubectl-krew"
krew_version: latest
krew_user: "{{ linux_username }}"
krew_plugins:
  - ingress-nginx

# nvm
nvm_profile: "/home/{{ linux_username }}/.bashrc"
nodejs_version: "16"
npm_packages:
  - "@nestjs/cli"
  - dotenv-cli

# pip
pip_packages:
  - pykerberos==1.2.4
  - pyvmomi==7.0.3

# resolv
resolv_nameserver: "10.0.2.11"
resolv_search: jerlyd.com

# shell
bash_profile_scripts:
  - ansible.sh
  - brew.sh
  - history.sh
  - krew.sh
  - kubectl-aliases.sh
  - kubectl-completion.sh
  - ssh.sh

# workspace
workspace_repos_dir: /home/{{ linux_username }}/source/repos
workspace_repos:
  - name: kubectl-aliases
    url: https://github.com/jeremyj563/kubectl-aliases.git
