---
# apt
apt_packages:
  - make
  - build-essential
  - libssl-dev
  - apt-transport-https
  - apt-file
  - bash-completion
  - net-tools
  - dnsutils
  - iputils-ping
  - python3-pip
  - openssh-server
  - openssh-client
  - libkrb5-dev
  - krb5-user
  - locate
  - less
  - gcc
  - sudo
  - zsh
  - nano
  - neovim
  - git
  - tig
  - curl
  - wget
  - tmux
  - unzip
  - fzf

# brew
linuxbrew_install_tmp: /tmp/linuxbrew
linuxbrew_install_url: https://raw.githubusercontent.com/Homebrew/install/master/install.sh
brew_path: /home/linuxbrew/.linuxbrew/bin
brew_bin_path: "{{ brew_path }}/brew"
brew_packages:
  - bat
  - kubectl
  - helm
  - derailed/k9s/k9s
  - kubeseal
  - argocd
  - argocd-autopilot
  - krew
  - nvm
  - gh
  - pnpm
  - openssl
  - pyenv
  - poetry
  - Azure/kubelogin/kubelogin

# git
git_global_user_name: Jeremy Johnson
git_global_user_email: modernclassicgamer@gmail.com
git_global_credential_helper: store
git_global_core_filemode: "false"
git_global_safe_directory: "*"
git_global_ssl_verify: "false"

# krew
krew_bin_path: "{{ brew_path }}/kubectl-krew"
krew_version: latest
krew_user: "{{ linux_username }}"
krew_plugins:
  - ingress-nginx

# nvm
nvm_profile: "/home/{{ linux_username }}/.bashrc"
nodejs_version: "16"
npm_packages:
  - "@nestjs/cli"
  - dotenv-cli

# pip
pip_packages:
  - pykerberos==1.2.4
  - pyvmomi==7.0.3

# resolv
resolv_nameserver: "10.0.2.11"
resolv_search: jerlyd.com

# proxy
proxy_url: ""
no_proxy_csv: "localhost,127.0.0.1,.jerlyd.com"

# shell
bashrc_scripts:
  - aliases.sh
  - ansible.sh
  - brew.sh
  - history.sh
  - krew.sh
  - kubectl-aliases.sh
  - kubectl-completion.sh
  - ssh.sh

# workspace
workspace_default_dir: jeremyj563
workspace_repos_dir: /home/{{ linux_username }}/source/repos.personal
workspace_repos:
  - name: dotfiles
    url: https://github.com/jeremyj563/dotfiles.git
  - name: kubectl-aliases
    url: https://github.com/jeremyj563/kubectl-aliases.git
  - name: scripts
    url: https://gitlab.com/jmjohnson85/scripts.git
    dir: jmjohnson85
  - name: proxy-switcher
    url: https://github.com/jeremyj563/proxy-switcher.git
