---
# apt
apt_packages:
  - apache2-utils
  - apt-file
  - apt-transport-https
  - bash-completion
  - build-essential
  - curl
  - dnsutils
  - fzf
  - gcc
  - gnutls-bin
  - iputils-ping
  - jq
  - krb5-user
  - less
  - libkrb5-dev
  - libssl-dev
  - make
  - mlocate
  - nano
  - neovim
  - net-tools
  - openssh-client
  - openssh-server
  - python3-pip
  - sudo
  - tmux
  - tree
  - unzip
  - wget
  - zsh

# brew
linuxbrew_install_tmp: /tmp/linuxbrew
linuxbrew_install_url: https://raw.githubusercontent.com/Homebrew/install/master/install.sh
brew_path: /home/linuxbrew/.linuxbrew/bin
brew_bin_path: "{{ brew_path }}/brew"
brew_packages:
  - argocd
  - argocd-autopilot
  - Azure/kubelogin/kubelogin
  - bat
  - devspace
  - gh
  - git
  - helm
  - jsonnet
  - k9s
  - krew
  - kubectl
  - kubectx
  - kubeseal
  - kustomize
  - nvm
  - oh-my-posh
  - openssl
  - pnpm
  - poetry
  - pyenv
  - terraform
  - tig
  - yq

# git
git_global_user_name: Jeremy Johnson
git_global_user_email: modernclassicgamer@gmail.com
git_global_credential_helper: store
git_global_core_filemode: "false"
git_global_safe_directory: "*"
git_global_ssl_verify: "false"
git_global_aliases:
  co: checkout
  cob: checkout -b
  br: branch
  brd: branch -D
  w: worktree
  wls: worktree list
  wa: worktree add
  wrm: worktree remove
  wmv: worktree move

# krew
krew_bin_path: "{{ brew_path }}/kubectl-krew"
krew_version: latest
krew_user: "{{ linux_username }}"
krew_plugins:
  - ingress-nginx
  - resource-capacity

# nvm
nvm_install_path: "/home/{{ linux_username }}/.nvm"
nvm_shell_init_file: "/home/{{ linux_username }}/.profile"
nvm_node_version: lts
nvm_version: latest
nvm_npm_packages:
  - dotenv-cli
  - node-gyp

# pip
pip_packages:
  - awscliv2>=2.2.0
  - boto3>=1.26.155
  - bs4>=0.0.1
  - kubernetes>=26.1.0
  # - pykerberos==1.2.4
  # - pyvmomi==7.0.3
  - requests>=2.31.0
  - toml>=0.10.0

# resolv
resolv_nameserver: "10.0.2.11"
resolv_nameserver_fallback: "192.10.0.1"
resolv_search_domains: jerlyd.com

# proxy
proxy_url: http://proxy.rockwellcollins.com:9090
no_proxy_csv: 0.0.0.0,127.0.0.0/8,172.16.0.0/16,192.168.0.0/16,localhost,local,svc

# shell
bashrc_scripts:
  - aliases.sh
  - ansible.sh
  - brew.sh
  - curl.sh
  - history.sh
  - krew.sh
  - kubectl-aliases.sh
  - kubectl-completion.sh
  - oh-my-posh.sh
  - ssh.sh

# workspace
workspace_default_dir: jeremyj563
workspace_repos_dir: /home/{{ linux_username }}/source/repos.personal
workspace_repos:
  - name: dotfiles
    url: https://github.com/jeremyj563/dotfiles.git
  - name: kubectl-aliases
    url: https://github.com/jeremyj563/kubectl-aliases.git
  - name: scripts
    url: https://gitlab.com/jmjohnson85/scripts.git
    dir: jmjohnson85
  - name: proxy-switcher
    url: https://github.com/jeremyj563/proxy-switcher.git
workspace_touch_dirs:
  - /home/{{ linux_username }}/.aws
