---
- name: Include vars based on target domain [{{ target_domain }}]
  include_vars:
    dir: vars/{{ target_domain }}

- name: Print required vars for current role [{{ role_name }}]
  debug:
    msg:
    - "resolv_nameserver: {{ resolv_nameserver }}"
    - "resolv_nameserver_fallback: {{ resolv_nameserver_fallback }}"
    - "resolv_search_domains: {{ resolv_search_domains }}"

- name: Unlink /etc/resolv.conf
  become: true
  file:
    path: /etc/resolv.conf
    state: absent

- name: Configure /etc/resolv.conf
  become: true
  copy:
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: "0644"
    attr: +i
    content: |
      ## ansible managed file (wsl-setup)

      nameserver {{ resolv_nameserver }}
      nameserver {{ resolv_nameserver_fallback }}
      search {{ resolv_search_domains }}
