---
- name: Unlink /etc/resolv.conf
  become: true
  file:
    path: /etc/resolv.conf
    state: absent

- name: Configure /etc/resolv.conf
  become: true
  copy:
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: "0644"
    attr: +i
    content: |
      # ANSIBLE MANAGED FILE - wsl-setup

      nameserver {{ resolv_nameserver }}
      nameserver {{ resolv_nameserver_fallback }}
      search {{ resolv_search_domains }}
