---
- name: Unlink /etc/resolv.conf
  file:
    path: /etc/resolv.conf
    state: absent

- name: Configure /etc/resplv.conf
  copy:
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
    attr: +i
    content:
      |
      # Ansible managed
      
      nameserver {{ resolv_nameserver_primary }}
      nameserver {{ resolv_nameserver_secondary }}
      search {{ resolv_search }}
