---
- name: "Ensure directory exists: /home/{{ linux_username }}/.config"
  file:
    path: /home/{{ linux_username }}/.config
    state: directory
    mode: "0700"

- name: "Ensure directory exists: /home/{{ linux_username }}/.config/k9s"
  file:
    path: /home/{{ linux_username }}/.config/k9s
    state: directory
    mode: "0755"

- name: Configure /home/{{ linux_username }}/.config/k9s/config.yml
  copy:
    dest: /home/{{ linux_username }}/.config/k9s/config.yml
    owner: "{{ linux_username }}"
    group: "{{ linux_username }}"
    mode: "0644"
    content: |
      # Ansible managed
      ---
      k9s:
        refreshRate: 2
        maxConnRetry: 5
        enableMouse: false
        headless: false
        logoless: false
        crumbsless: false
        readOnly: false
        noIcons: false
        logger:
          tail: 100
          buffer: 5000
          sinceSeconds: -1
          fullScreenLogs: false
          textWrap: false
          showTime: false
        currentContext: ""
        currentCluster: ""
        clusters:
          "":
            namespace:
              active: default
              favorites:
              - default
            view:
              active: po
            featureGates:
              nodeShell: false
            shellPod:
              image: busybox:1.31
              command: []
              args: []
              namespace: default
              limits:
                cpu: 100m
                memory: 100Mi
            portForwardAddress: localhost
        thresholds:
          cpu:
            critical: 90
            warn: 70
          memory:
            critical: 90
            warn: 70
        screenDumpDir: /tmp/k9s-screens-wsl
