---
- name: Create script /home/{{ linux_username }}/.bash_profile
  copy:
    src: .bash_profile
    dest: /home/{{ linux_username }}/.bash_profile
    owner: "{{ linux_username }}"
    group: "{{ linux_username }}"
    mode: '0644'

- name: Create directory /home/{{ linux_username }}/.bash_profile.d
  file:
    path: /home/{{ linux_username }}/.bash_profile.d
    state: directory
    owner: "{{ linux_username }}"
    group: "{{ linux_username }}"
    mode: '0755'

- name: Create scripts in /home/{{ linux_username }}/.bash_profile.d
  copy:
    src: "{{ script }}"
    dest: "/home/{{ linux_username }}/.bash_profile.d/{{ script }}"
    owner: "{{ linux_username }}"
    group: "{{ linux_username }}"
    mode: '0644'
  with_items: "{{ bash_profile_scripts }}"
  loop_control:
    loop_var: script
  