---
- name: Install nvm, nodejs, and global npm packages
  import_role:
    name: morgangraphics.ansible_role_nvm
  vars:
    nvm_commands:
    - "nvm exec default npm install --global {{ nvm_npm_packages | join('\n') }}"