# EXAMPLE:
# ansible-playbook playbook-wsl-config.yml
#
# ansible-playbook playbook-wsl-config.yml -e "linux_username=wsl"
#
# ansible-playbook playbook-wsl-config.yml -e "linux_username=wsl linux_password=<password>"
---
- hosts: localhost
  vars_prompt:
    - name: linux_username
      prompt: "Linux username"
    - name: linux_password
      prompt: "Linux password"
      private: yes
  vars:
    ansible_become_password: "{{ linux_password }}"
  roles:
    - shell
    - apt
    - brew
    - krew
    - nvm
