- hosts: localhost
  vars_files:
    - vars/apt_packages.yml
    - vars/brew_packages.yml
    # - vars/language_versions.yml
    # - vars/tool_versions.yml
  roles:
    - shell
    - apt
    - brew
    - nvm
    # - workspace
    # - ops
    # - dev
