# EXAMPLE:
# ansible-playbook playbook-wsl-user.yml
#
# ansible-playbook playbook-wsl-user.yml -e "linux_username=wsl"
#
# ansible-playbook playbook-wsl-user.yml -e "linux_username=wsl linux_password=<password>"
---
- hosts: localhost
  vars_prompt:
    - name: linux_username
      prompt: "Linux username"
    - name: linux_password
      prompt: "Linux password"
      private: yes
  roles:
    - user