# EXAMPLE:
# ansible-playbook playbook-wsl-config.yml
---
- hosts: localhost
  vars_prompt:
    - name: linux_username
      prompt: "Linux username"
      private: no
    - name: linux_password
      prompt: "Linux password"
      private: yes
  vars:
    ansible_become_password: "{{ linux_password }}"
  roles:
    - apt
    - binaries
    - brew
    - git
    - helm
    - k9s
    - krew
    - nvm
    - pip
    - shell
    - workspace
