---
- src: morgangraphics.ansible_role_nvm # https://github.com/morgangraphics/ansible-role-nvm
  version: v1.4.3
- src: markosamuli.linuxbrew # https://github.com/markosamuli/ansible-linuxbrew
  version: v1.2.2
