---
- name: Update apt package list
  become: true
  package:
    update_cache: yes

- name: Upgrade all apt packages
  become: true
  package:
    name: '*'
    state: latest

- name: Install apt packages
  become: true
  apt:
    name: "{{ apt_packages }}"
