---
- name: Update apt package list
  package:
    update_cache: yes
  become: true

- name: Upgrade all apt packages
  package:
    name: '*'
    state: latest
  become: true

- name: Install apt packages
  apt:
    name: "{{ apt_packages }}"
  become: true
