---
- name: Set proxy config in /etc/apt/apt.conf.d/05proxy
  become: true
  blockinfile:
    path: "/etc/apt/apt.conf.d/05proxy"
    create: true
    mode: "0644"
    owner: root
    group: root
    block: |
      Acquire::http::Proxy "{{ proxy_url }}";
