---
- name: Create workspace directory {{ workspace_dir }}
  file:
    path: "{{ workspace_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0755'

- name: Clone workspace git repos
  git:
    repo: "{{ repo.url }}"
    dest: "{{ workspace_dir }}/{{ repo.name }}"
  with_items: "{{ workspace_repos }}"
  loop_control:
    loop_var: repo
