---
- import_tasks:
    file: repos.yaml

- import_tasks:
    file: dotfiles.yaml
  vars:
    dotfiles_repo: "{{ workspace_repos | selectattr('name', '==', 'dotfiles') | first }}"

- import_tasks:
    file: dirs.yaml
