---
- name: Generate an OpenSSH keypair of type {{ workspace_ssh_keypair_type }}
  community.crypto.openssh_keypair:
    path: /home/{{ linux_username }}/.ssh/id_{{ workspace_ssh_keypair_type }}
    type: "{{ workspace_ssh_keypair_type }}"
