---
- name: Check if OpenSSH private key already exists [/home/{{ linux_username }}/.ssh/id_{{ workspace_ssh_keypair_type }}]
  stat:
    path: /home/{{ linux_username }}/.ssh/id_{{ workspace_ssh_keypair_type }}
  register: stat_keypair

- name: Generate an OpenSSH keypair of type {{ workspace_ssh_keypair_type }}
  community.crypto.openssh_keypair:
    path: /home/{{ linux_username }}/.ssh/id_{{ workspace_ssh_keypair_type }}
    type: "{{ workspace_ssh_keypair_type }}"
    owner: "{{ linux_username }}"
    group: "{{ linux_username }}"
    force: false
    mode: 600
  when: not stat_keypair.stat.exists
