---
- name: Install and upgrade brew packages
  community.general.homebrew:
    path: "{{ brew_path }}"
    name: "{{ brew_packages }}"
    update_homebrew: true
    upgrade_all: true
  environment:
    HOMEBREW_NO_ANALYTICS: 1
