---
- name: "Set Git global user.name to {{ git_global_user_name }}"
  git_config:
    name: user.name
    scope: global
    value: "{{ git_global_user_name }}"

- name: "Set Git global user.email to {{ git_global_user_email }}"
  git_config:
    name: user.email
    scope: global
    value: "{{ git_global_user_email }}"

- name: "Set Git global credential.helper to {{ git_global_credential_helper }}"
  git_config:
    name: credential.helper
    scope: global
    value: "{{ git_global_credential_helper }}"
