---
- name: Set Git global aliases
  include_tasks: alias.yml
  vars:
    git_config_alias_name: "{{ alias.key  }}"
    git_config_alias_value: "{{ alias.value }}"
    git_config_scope: global
  with_items: "{{ git_global_aliases | dict2items(key_name='key', value_name='value') }}"
  loop_control:
    loop_var: alias
    label: "{{ alias.key }}"

- import_tasks: core.yml
- import_tasks: credential.yml
- import_tasks: http.yml
- import_tasks: safe.yml
- import_tasks: user.yml
