---
- name: Create config file /etc/wsl.conf
  copy:
    owner: root
    group: root
    mode: '0644'
    dest: /etc/wsl.conf
    content:
      |
      # Ansible managed

      [user]
      default=wsl

      [network]
      generateResolvConf = false
  become: true
