---
- name: Configure /etc/wsl.conf
  become: true
  copy:
    dest: /etc/wsl.conf
    owner: root
    group: root
    mode: "0644"
    content: |
      # ANSIBLE MANAGED FILE - wsl-setup

      [user]
      default = {{ linux_username }}

      [network]
      generateResolvConf = false

      [automount]
      options = "metadata"
