---
- name: Configure /etc/wsl.conf
  copy:
    dest: /etc/wsl.conf
    owner: root
    group: root
    mode: '0644'
    content:
      |
      # Ansible managed

      [user]
      default = {{ linux_username }}

      [network]
      generateResolvConf = false
